# Generated by cucumber-sinatra. (2011-03-09 09:34:14 -0500)

ENV['RACK_ENV'] = 'test'

require_relative '../../app.rb'

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MyApp

class MyAppWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyAppWorld.new
end
